### ISSUE TITLE
-G option raises NameError on a file tree.

### ISSUE THREAD

**Issue by sciunto** [backupchecker/backupchecker#15]
Hi,

I just watched your conference at RMLL. All my backups are flat trees. A quick remark about your documentation is that it's pretty centred on archives. I use trees with hardlinks to save disk space and preserve CPU during backups.

As far as I understand the doc, the -G option should generate the conf files also for flat trees. I guess this is not expected. I'm running archlinux, but it shouldn't be important here.

~~~
[fr:~]  % backupchecker -v
backupchecker 1.7
[fr:~] % backupchecker -G ~/backup_clematite/sciuntofr
Traceback (most recent call last):
  File "/usr/bin/backupchecker", line 20, in <module>
    Main()
  File "/usr/lib/python3.4/site-packages/backupchecker/main.py", line 32, in __init__
    self.__main()
  File "/usr/lib/python3.4/site-packages/backupchecker/main.py", line 47, in __main
    ListType(__options)
  File "/usr/lib/python3.4/site-packages/backupchecker/listtype.py", line 36, in __init__
    self.__main(__options)
  File "/usr/lib/python3.4/site-packages/backupchecker/listtype.py", line 62, in __main
    self.__bck = GenerateListForTree(__genparams)
  File "/usr/lib/python3.4/site-packages/backupchecker/generatelist/generatelistfortree.py", line 169, in __init__
    str(__fileinfo.st_mtime)))
NameError: name '_GenerateListForTree__fileinfo' is not defined
~~~

**Comment by chaica** [comment]
Thanks for your bug report, I'll investigate. Just a question, what is you Python version?

**Comment by sciunto** [comment]
~~~
[fr:~] % python -V
Python 3.4.3
~~~

**Comment by backupchecker** [comment]
ok got it, typo in a untested corner case. Thanks for your report. I'll fix it right away.
