### ISSUE TITLE
backupchecker

### ISSUE THREAD

**Issue by ikyuki** [backupchecker/backupchecker#16]
Hello,
 I'm working on a project, and I’m trying to perform a check using backup checker to verify the backup integrity but as i perform it i get this:

Traceback (most recent call last):
  File "/usr/bin/backupchecker", line 20, in <module>
    Main()
  File "/usr/local/lib/python3.4/dist-packages/backupchecker/main.py", line 32, in __init__
    self.__main()
  File "/usr/local/lib/python3.4/dist-packages/backupchecker/main.py", line 47, in __main
    ListType(__options)
  File "/usr/local/lib/python3.4/dist-packages/backupchecker/listtype.py", line 36, in __init__
    self.__main(__options)
  File "/usr/local/lib/python3.4/dist-packages/backupchecker/listtype.py", line 71, in __main
    self.__bck = GenerateListForTar(__genparams)
  File "/usr/local/lib/python3.4/dist-packages/backupchecker/generatelist/generatelistfortar.py", line 53, in __init__
    self.__main(__tar)
  File "/usr/local/lib/python3.4/dist-packages/backupchecker/generatelist/generatelistfortar.py", line 80, in __main
    __type = self.__translate_type(__tarinfo.type)
  File "/usr/local/lib/python3.4/dist-packages/backupchecker/generatelist/generatelistfortar.py", line 244, in __translate_type
    return __types[__arctype]
KeyError: b'D'
  What can i do to resolve it?

Cheers, thanks

**Comment by backupchecker** [comment]
Could you copy/paste the full command line you executed in order I read what exactly you required?

**Comment by ikyuki** [comment]
it's just a test to before adding it to a script

backupchecker -G /home/xxxx-Latitude-home.tar.gz

I'm doing some tests before the implementation to the production.. On the VM every thing was good, but now that i'm trying on the physical machine, i have this issue

**Comment by ikyuki** [comment]
I'm not able to generate the conf file

**Comment by backupchecker** [comment]
Can I ask you also the version of Backup Checker you are using ? You can get it with:
```
$ backupchecker --version
```

**Comment by ikyuki** [comment]
1.7

**Comment by backupchecker** [comment]
Interesting, can you tell me what your operation system is (Linux? other?) and what version of python you're using while launching backupchecker ? You can get it with something like:
```
BCKCHK=`whereis backupchecker  | cut -d" " -f2`
head -n 5 $BCKCHK
echo $BCKCHK
```

**Comment by ikyuki** [comment]
I'm using ubuntu 15.10 and python3.4

**Comment by backupchecker** [comment]
That's weird, tarfile Python module is getting a type identified by b"D" but in the source file of Lib/tarfile.py I don't read any b"D" available haha :| 
Is it a tar archive from a linux system? Sorry keep questioning you but this bug is not an easy one for now.

**Comment by ikyuki** [comment]
Yes it's a tar archive from a linux system,a backup that i made with backup-manager, but as i explained to you before, the first time everything worked perfectly.

**Comment by backupchecker** [comment]
what do you mean by "the first time" ? Can you tell me the different steps you did like:
1. I created the backup  with backup-manager
2. I did a: backupchecker -G /home/xxxx-Latitude-home.tar.gz
2. I also did that...

Because I need to know whats steps you followed in order to understand the current situation.

**Comment by ikyuki** [comment]
The first time, i created the backup whit backup-manager, then i used the different steps to perform the check... Generating the files .conf & .list and the scan using -c... After that i modified my backup in purpose to get the output of the log file...Everything worked as i expected
That was the first step to pick up the backupchecker to verify the integrity of the backups of the company.
Now i'm trying to use do the same to chek the integrity end then use the log file to send an alert to nagios... But get this issue while trying to generate the files...
