### ISSUE TITLE
"UID/GID not found" crash backupchecker

### ISSUE THREAD

**Issue by lord-re** [backupchecker/backupchecker#23]
When used with -g , backupchecker will crash when it encounters a file with an unknown UID or GID.
Steps to reproduce : 
 1 : touch /tmp/badfile
 2 : chown 1234:1234 /tmp/badfile
 3 : backupchecker -g /tmp
 4 : enjoy

Here is a trackback :
```
Traceback (most recent call last):
  File "/usr/bin/backupchecker", line 20, in <module>
    Main()
  File "/usr/lib64/python3.4/site-packages/backupchecker/main.py", line 32, in __init__
    self.__main()
  File "/usr/lib64/python3.4/site-packages/backupchecker/main.py", line 47, in __main
    ListType(__options)
  File "/usr/lib64/python3.4/site-packages/backupchecker/listtype.py", line 36, in __init__
    self.__main(__options)
  File "/usr/lib64/python3.4/site-packages/backupchecker/listtype.py", line 62, in __main
    self.__bck = GenerateListForTree(__genparams)
  File "/usr/lib64/python3.4/site-packages/backupchecker/generatelist/generatelistfortree.py", line 139, in __init__
    pwd.getpwuid(self.__fileinfo.st_uid).pw_name,
KeyError: 'getpwuid(): uid not found: 1234'
```

**Comment by backupchecker** [comment]
Confirmed. Will have a look at is asap. Thanks for the report.

**Comment by lordtoniok** [comment]
Thanks.
I don't know if it's possible but instead of trying to map the uid/gid to a username/group can't it just store the uid/gid value ?

**Comment by lord-re** [comment]
thanks, will try it ;-)

**Comment by chaica** [comment]
not forgetting to release but I have to fix some functional tests before.

**Comment by lord-re** [comment]
I tried the 1.9 and still got an error but when i check : 

`Traceback (most recent call last):
  File "/usr/bin/backupchecker", line 20, in <module>
    Main()
  File "/usr/lib64/python3.4/site-packages/backupchecker/main.py", line 32, in __init__
    self.__main()
  File "/usr/lib64/python3.4/site-packages/backupchecker/main.py", line 40, in __main
    CheckBackups(__confs.configs, __options)
  File "/usr/lib64/python3.4/site-packages/backupchecker/checkbackups/checkbackups.py", line 42, in __init__
    self.__main(__confs, __options)
  File "/usr/lib64/python3.4/site-packages/backupchecker/checkbackups/checkbackups.py", line 50, in __main
    __bck = CheckTree(__cfgvalues, __options)
  File "/usr/lib64/python3.4/site-packages/backupchecker/checkbackups/checkarchive.py", line 49, in __init__
    self._main(_cfgvalues, _options)
  File "/usr/lib64/python3.4/site-packages/backupchecker/checkbackups/checktree.py", line 47, in _main
    'gname': grp.getgrgid(__dirinfo.st_gid).gr_name,
KeyError: 'getgrgid(): gid not found: 1018'`
